# Generated by Django 4.2.1 on 2023-05-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(db_index=True)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
        ),
    ]
