name: "Call: prod cli"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  logs:
    runs-on: [ self-hosted, prod ]
    steps:
      - name: Logs
        run: |
          cd /home/user/work/site-api/site-api
          docker-compose down -v
