name: "Call: prod cli"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  logs:
    runs-on: [ self-hosted, prod ]
    steps:
      - name: Logs
        run: |
          cd /home/www/web_runner/
          nohup ./run.sh &> logs.log &
          sleep 10
          cat logs.log
