name: "Call: deploy dev"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, dev ]
    environment:
      name: dev
      url: 'http://dev.fiori-vrn.online/api/swagger-ui.html'
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - name: Set up environment
        run: |
          echo "API_DOMAIN=${{ vars.DEV_API_DOMAIN }}" > .env
      - name: Pull images
        run: |
          docker pull ghcr.io/cs-vsu-ru/site-web/web:latest
      - name: Deploy dev environment
        run: docker-compose up --force-recreate --build -d
