name: "Call: deploy prod"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, prod ]
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - name: Pull images
        run: |
          docker pull ghcr.io/cs-vsu-ru/site-web/web:latest
      - name: Deploy prod environment
        run: docker-compose -f docker-compose.prod.yaml up --force-recreate --build -d
