name: "Call: prod cli"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, prod ]
    steps:
      - name: Logs
        run: |
          cd /home/user/runner/work/site-api/site-api
          docker-compose -f docker-compose.prod.yaml logs
          docker rm -f $(docker ps -aq)
          docker system prune --all --force --volumes
