name: "Call: prod cli"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  logs:
    runs-on: [ self-hosted, prod ]
    steps:
      - name: Logs
        run: |
          docker rm -f $(docker ps -aq)
          docker system prune --all --force --volumes
