name: "Call: prod cli"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  logs:
    runs-on: [ self-hosted, prod ]
    steps:
      - name: Logs
        run: |
          docker exec -t site-api-api-1 ls /api/files
