name: "Call: deploy dev"

on:
  workflow_call:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: [ self-hosted, dev ]
    environment:
      name: dev
      url: 'http://83.69.248.136/swagger-ui.html'
    steps:
      - uses: actions/checkout@v3.5.2
        with:
          clean: false
      - name: Deploy dev environment
        run: docker-compose up --build -d
